### ISSUE TITLE
using ai spawner

### ISSUE THREAD

**Issue by deathking61** [Blu-x92/LunasFlightSchool#3]
so when using the spawner the planes are immune to acf missiles..............why?

**Comment by Blu-x92** [comment]
im guessing because you are using some kind or prop or damage protector that prevents damage on world entities (Planes spawned by the ai spammer are owned by world)

**Comment by deathking61** [comment]
The only thing I have is no mad pp so

**Comment by Blu-x92** [comment]
well, doesnt matter whats causing it, this doesn't seem like an lfs issue because ACF uses its own damage system. There isn't anything i can do from my side.

**Comment by deathking61** [comment]
ok so i just talked to the acf missiles dev and he told me they should be able to so its on your code thats preventing it all please change it thanks

**Comment by Blu-x92** [comment]
doubt. The way you described it, it only happens with the ai-spammer and planes spawned by the ai-spammer use same exact code as normal spawned planes. The only difference is that they have no Owner and this probably prevents damage depending on damage protector or acf settings…
Whatever, since i dont use acf, i dont care, if you think this is lfs related just fix it yourself and make a pullrequest. Will not waste my time looking through acf's entire damage code

**Comment by deathking61** [comment]
well, can it be made to be owned by the person who owns the spawner,
please? cause I don't have anything that would prevent it from being killed.
